---
title       : Predictors of MPG using mtcars Dataset
subtitle    : 
author      : Michael Lamanuzzi
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Context

This project was created to fulfill the requirements of the Developing Data Products Coursera course from Johns Hopkins University.

The purpose of the project was to get familiar with developing an interactive Shiny application and reprodicible pitch using Slidify.

The data for the app was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models).

--- .class #id 

## Summary of Data

```{r}
summary(mtcars)
```

--- .class #id 

## Using the app

The app will allow the user to visualize features of the dataset as predictors of MPG.

To use the app, simply choose the predictor of MPG that you would like to investigate.

Once chosen, a linear model is built using the selected predictor with respect to mpg, and the regression line drawn.

A summary table is also shown of that variable in the dataset.

--- .class #id 
## Summary

[Source code on Github](https://github.com/mlamanuzzi/MPGPredictors)